### ISSUE TITLE
Events: Data Sharing for Open Access class

### ISSUE THREAD

**Issue by saragon02** [galterdatalab/galterdatalab.github.io#6]
The DOI is for a different class, "Best Practices in Research Data Management and Data Sharing." The Open Access class slides aren't deposited yet, but the registration site is available at: https://www.eventbrite.com/e/researchers-toolkit-data-sharing-for-open-access-registration-59786871141?aff=erelexpmlt

**Comment by carsonicator** [comment]
Thanks for the correction. I switched the link to the registration site.
